metric: VOC
map_type: integral
num_classes: 1

TrainDataset:
  name: VOCDataSet
  allow_empty: true
  dataset_dir: PP/dataset/
  anno_path: train.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  allow_empty: true
  dataset_dir: PP/dataset/
  anno_path: test.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: PP/dataset/label_list.txt
